#ecommerce_ecommerce_homepage:
#    path:     /
#    defaults: { _controller: EcommerceEcommerceBundle:pages:index }

list_product:
    path:     /
    defaults: { _controller: EcommerceEcommerceBundle:Products:listProduct }

add_basket:
    path:     /addBasket/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Basket:addBasket }

delete_basket:
    path:     /deleteBasket/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Basket:deleteBasket }

basket:
    path:     /basket
    defaults: { _controller: EcommerceEcommerceBundle:Basket:basket }

deliver:
    path:     /deliver
    defaults: { _controller: EcommerceEcommerceBundle:Basket:deliver }

validate:
    path:     /validate
    defaults: { _controller: EcommerceEcommerceBundle:Basket:validate }

product_info:
    path:     /productInfo/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Products:productInfo }

categoriesProducts:
    path:     /category/{category}
    defaults: { _controller: EcommerceEcommerceBundle:Products:category }

searchProducts:
    path:     /search
    defaults: { _controller: EcommerceEcommerceBundle:Products:searchResult}