ecommerce_ecommerce_adminProducts:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing/routingProductsAdmin.yml"
    prefix:   /admin/products

ecommerce_ecommerce_adminCommandes:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
    prefix:   /admin/commandes

list_product:
    path:     /
    defaults: { _controller: EcommerceEcommerceBundle:Products:listProduct }

add_basket:
    path:     /addBasket/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Basket:addBasket }

delete_basket:
    path:     /deleteBasket/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Basket:deleteBasket }

basket:
    path:     /basket
    defaults: { _controller: EcommerceEcommerceBundle:Basket:basket }

deliver:
    path:     /basket/deliver
    defaults: { _controller: EcommerceEcommerceBundle:Basket:deliver }

validate:
    path:     /basket/validate
    defaults: { _controller: EcommerceEcommerceBundle:Basket:validate }

product_info:
    path:     /productInfo/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Products:productInfo }

categoriesProducts:
    path:     /category/{category}
    defaults: { _controller: EcommerceEcommerceBundle:Products:listProduct }

searchProducts:
    path:     /search
    defaults: { _controller: EcommerceEcommerceBundle:Products:searchResult}

delete_address_deliver:
    path:     /deliver/address/deleted/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Basket:deleteAddress }

prepare:
    path:     /prepare
    defaults: { _controller: EcommerceEcommerceBundle:Commande:prepareOrdered }

validate_ordered:
    path:     /api/paypal/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Commande:validateOrdered }