# Declaration de notre extension twig en Service pour la rendre utilisable
services:
    sendMailer:
      class: Ecommerce\EcommerceBundle\Services\SendMailer
      arguments: ['@service_container']

    setNewBill:
      class: Ecommerce\EcommerceBundle\Services\GetBill
      arguments: ['@service_container']

    setNewReference:
      class: Ecommerce\EcommerceBundle\Services\GetReference
      arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']

    tva:
      class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }

    montantTva:
      class: Ecommerce\EcommerceBundle\Twig\Extension\MontantTvaExtension
      tags:
        - { name: twig.extension }

    redirection_listener:
      class: Ecommerce\EcommerceBundle\EventListener\RedirectionListener
      arguments: ['@service_container', '@session']
      tags:
        - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
