<?php

namespace Users\UsersBundle\Repository;

/**
 * UsersAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
