imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    product_images: '%kernel.root_dir%/../web/uploads'

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        phone: 6 90 71 09 15
        fax: 6 94 99 12 97
        localisation: Douala-Koumassi
        Enterprise: HitechElectronics

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        url: 
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          JMSPaymentCoreBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    encryption: tls
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Users\UsersBundle\Entity\Users
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

jms_payment_core:
    encryption:
        secret: def0000028b8059819801fbe608c167f4624da898c13a43fbc2389b755b55495a0041882606c2da2fbb32d2bea3f33ab507370ca390369aab52894c0fa11eb31f8da3c82

jms_payment_paypal:
    username: your_api_username # not your account username
    password: your_api_password # not your account password
    signature: your_api_signature
    return_url:
    cancel_url:
    notify_url:
    useraction: commit

knp_paginator:
  page_range: 5
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
  template:
    pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v4_pagination.html.twig'
    sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig'

#liip_imagine:
#    # As mentioned above, gd, imagick or gmagick are possible
#    driver: "imagick"
#    resolvers:
#        defaults:
#            web_path: ~
#
#    # This is where all the filters sets are located
#    filter_sets:
#        square: # The name of the filter, can be later used in the twig template
#            quality: 75 # Compression quality, this image will be 75% the quality
#            filters: # These are the filters of the filter set, many filters can be applied
#               # Scale and shrink the image to the given size, with a possible crop of the image
#               thumbnail:
#                    size: [200, 200]
#                    mode: outbound
#
#        # Shrink the image to 350px wide, the image will keep aspect ratio and adapt the height accordingly
#        small:
#            quality: 80
#            filters:
#                relative_resize:
#                    widen: 350
#
#        # Shrink/upscale the image to 800px of height, with full quality
#        big:
#            filters:
#                relative_resize:
#                    heighten: 800
#                    # Will allow smaller images to take 800px of height,
#                    # width will change accordingly since aspect ration is still valid.
#                    allow_upscale: true