#_liip_imagine:
#    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"  

users_users:
    resource: "@UsersUsersBundle/Resources/config/routing.yml"
    prefix:   /

pages_pages:
    resource: "@PagesPagesBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce_ecommerce:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
