users_users_users:
    resource: "@UsersUsersBundle/Resources/config/routing/routingUsers.yml"
    prefix:   /

users_users_adminUsers:
    resource: "@UsersUsersBundle/Resources/config/routing/routingUsersAdmin.yml"
    prefix:   /admin/users