<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function byBill($user)
    {
        $queryBuilder = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.users = :user')
            ->andWhere('c.validate = 1')
            ->andWhere('c.reference != 0')
            ->orderBy('c.id')
            ->setParameter('user', $user);

        return $queryBuilder->getQuery()->getResult();
    }

    public function byDateCommand($date)
    {
        $queryBuilder = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.date > :date')
            ->andWhere('c.validate = 1')
            ->orderBy('c.id')
            ->setParameter('date', $date);

        return $queryBuilder->getQuery()->getResult();
    }
}
