<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
        $queryBuilder = $this->createQueryBuilder('p')
                             ->select('p')
                             ->where('p.id IN (:array)')
                             ->setParameter('array', $array);
        return $queryBuilder->getQuery()->getResult();
    }

    public function byCategory($category)
    {
        $queryBuilder = $this->createQueryBuilder('p')
                             ->select('p')
                             ->where('p.category = :category')
                             ->andWhere('p.available = 1')
                             ->orderBy('p.id')
                             ->setParameter('category', $category);

        return $queryBuilder->getQuery()->getResult();
    }

//    select * from product p where p.name = :tag and p.available = 1
//    orderBy p.id;
    public function search($tag)
    {
        $queryBuilder = $this->createQueryBuilder('p')
                             ->select('p')
                             ->where('p.name like :tag')
                             ->andWhere('p.available = 1')
                             ->orderBy('p.id')
                             ->setParameter('tag', $tag);

        return $queryBuilder->getQuery()->getResult();
    }
}
