<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategory($category)
    {
        $queryBuilder = $this->createQueryBuilder('p')
                             ->select('p')
                             ->where('p.category = :category')
                             ->orderBy('p.id')
                             ->setParameter('category', $category);
        return $queryBuilder->getQuery()->getResult();
    }
}
